#!/bin/bash

cd /tmp/rom

. build/envsetup.sh
lunch fluid_certus-userdebug
export SELINUX_IGNORE_NEVERALLOWS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 50G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	make api-stubs-docs -j8
	make system-api-stubs-docs -j8
	make test-api-stubs-docs -j8
}

make_rom(){
	make bacon -j8
	zip=$(up out/target/product/certus/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
sleep 4200 && kill "$!"
