#!/bin/bash

ROMDIR=/tmp/rom
MANIFEST=https://github.com/Project-Fluid/manifest.git
BRANCH=fluid-11

mkdir -p "$ROMDIR"
cd "$ROMDIR"

# Repo init command
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name awikawok1
git config --global user.email awikawok@protonmail.com

git clone https://github.com/awikawok1/local_manifests --depth 1 -b certus/11 .repo/local_manifests

# Sync source with -q
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Replace LatinIME to modified LatinIME for better interface :p
rm -rf packages/inputmethods/LatinIME
git clone https://github.com/AOSiP/platform_packages_inputmethods_LatinIME -b eleven packages/inputmethods/LatinIME

# For fix RIL problem in LOS Android Q based ROM
#rm -rf packages/services/Telephony
#git clone https://github.com/LineageOS/android_packages_services_Telephony -b lineage-17.1 packages/services/Telephony

# Codec Patch maybe :p
cd frameworks/av
wget https://github.com/SamarV-121/android_vendor_extra/raw/lineage-18.1/patches/frameworks/av/0005-Don-t-fail-AAC-decoding-if-DRC-parameter-isn-t-avail.patch
git am 0005-Don-t-fail-AAC-decoding-if-DRC-parameter-isn-t-avail.patch
cd /tmp/rom

# Fix Hotspot in R
cd system/netd
wget https://github.com/phhusson/platform_system_netd/commit/0296b55efeaae8cc835a6e2645531b29e10fb934.patch
git am 0296b55efeaae8cc835a6e2645531b29e10fb934.patch
cd /tmp/rom

# Fix Install folder gone issue
#cd build/make
#wget https://github.com/Komodo-OS-Rom/build/commit/298ea6830037c69b5299f57b6cc3aefe04ad9ae5.patch
#git am 298ea6830037c69b5299f57b6cc3aefe04ad9ae5.patch
#cd /tmp/rom
